spring.application.name=service-registry

eureka.client.register-with-eureka= false
eureka.client.fetch-registry=false

eureka.instance.hostname=localhost

server.port=9090

eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
