spring.application.name=gateway-service

server.port=8090
eureka.client.service-url.defaultZone=http://localhost:8080/eureka

spring.cloud.gateway.server.webmvc.routes[0].id=authservice
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTHSERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=path=/v1/auth/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1


spring.cloud.gateway.server.webmvc.routes[1].id=adminservice
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ADMINSERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=path=/v1/admin/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=hospitalservice
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://HOSPITALSERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=path=/v1/hospital/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[3].id=donorservice
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://DONORSERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=path=/v1/donor/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1

server.servlet.context-path=/gateway

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

