spring.application.name=admin-manager-service
server.port=8086
# Eureka config
eureka.client.service-url.defaultZone=http://localhost:8080/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.boot.admin.discovery.ignored-services=admin-manager-service

spring.security.user.name=user
spring.security.user.password=pass