spring.boot.admin.url = http://localhost:1010/

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
server.port=1010

spring.application.name=adminserver
eureka.client.service-url.defaultZone=http://localhost:9090/eureka

eureka.instance.prefer-ip-address=true
management.endpoint.health.show-details=always
